exclude: '^$'
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-toml
    - id: trailing-whitespace
    - id: check-ast
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
   - id: flake8
     types: [ python ]
     args: [--max-line-length, "100"]
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports
      language_version: python3
