[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dummy-python-project"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "pre-commit"
]

